import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const base = process.env.IPPO_TEST_URL || 'http://127.0.0.1:8787';
await mkdir('artifacts', { recursive: true });
const browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHROME_CHANNEL || undefined, headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
await page.goto(base);
await page.getByRole('heading', { name: '今日は、どんな一日？' }).waitFor();
await page.screenshot({path:'artifacts/desktop-ja.png',fullPage:true});
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
await page.getByRole('combobox').selectOption('ko');
await page.getByRole('textbox').fill('조금 지친 것 같아요');
await page.getByRole('button', {name:'메시지 보내기',exact:true}).click();
await page.locator('.message-row.assistant').waitFor();
assert.equal(await page.evaluate(() => localStorage.getItem('ippo.history.v1')), null);
await page.reload();
await page.getByRole('heading',{name:'오늘은 어떤 하루였나요?'}).waitFor();
await page.locator('.desktop-nav').getByRole('button',{name:'작은 한 걸음',exact:true}).click();
await page.getByRole('button',{name:'에너지 1: 쉬어가는 모드',exact:true}).click();
assert.equal(await page.getByRole('button',{name:'에너지 1: 쉬어가는 모드',exact:true}).evaluate(el=>document.activeElement===el),true,'energy selection keeps keyboard focus');
await page.getByRole('button',{name:'이 한 걸음 시작하기',exact:true}).click();
await page.getByRole('button',{name:'해냈어요',exact:true}).click();
assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('ippo.step.v1')).status),'completed');
await page.locator('.desktop-nav').getByRole('button',{name:'설정',exact:true}).click();
await page.getByRole('switch').check();
await page.getByRole('button',{name:'한국',exact:true}).click();
assert.ok(await page.getByRole('link').filter({hasText:'109'}).getAttribute('href') === 'https://www.129.go.kr/109');
await page.locator('.desktop-nav').getByRole('button',{name:'이야기',exact:true}).click();
await page.getByRole('textbox').fill('오늘 기분 좋았던 일');
await page.getByRole('button',{name:'메시지 보내기',exact:true}).click();
await page.locator('.message-row.assistant').waitFor();
await page.reload();
await page.locator('.message-row.assistant').waitFor();
assert.equal(await page.locator('.message-bubble').count(),2);
await page.locator('.desktop-nav').getByRole('button',{name:'설정',exact:true}).click();
const downloadPromise=page.waitForEvent('download');
await page.getByRole('button',{name:'대화 내보내기',exact:true}).click();
assert.match((await downloadPromise).suggestedFilename(),/^ippo-.*\.txt$/);
await page.getByRole('button',{name:'대화·한 걸음 기록 지우기',exact:true}).click();
await page.getByRole('button',{name:'기록 지우기',exact:true}).click();
assert.equal(await page.evaluate(()=>localStorage.getItem('ippo.history.v1')),null);
assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('ippo.step.v1')).status),'suggested');
await page.locator('.desktop-nav').getByRole('button',{name:'이야기',exact:true}).click();
if (await page.locator('.toast button').count()) await page.locator('.toast button').click();
await page.screenshot({path:'artifacts/desktop-ko.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'artifacts/mobile-ko.png',fullPage:true});
for (const name of ['작은 한 걸음','설정','이야기']) {
  await page.locator('.mobile-nav').getByRole('button',{name,exact:true}).click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true,`mobile overflow ${name}`);
}
await page.getByRole('combobox').selectOption('ja');
await page.screenshot({path:'artifacts/mobile-ja.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true);
assert.deepEqual(errors,[]);
console.log('PASS: ja/ko 1440/390 layouts, demo chat, default privacy, opt-in persistence, mission completion, region links, export and delete; no console/page errors.');
await browser.close();
